#! /bin/bash
P=$1
Q=$2
p=${P%.*}
echo $p
if [ $p -eq 1 ]; then
    halcmd setp gasketing.flushing.on True
    echo  "Промывка включение"
else
    halcmd setp gasketing.flushing.on False
    echo  "Промывка выключение"
fi

exit 0
