#! /bin/bash
P=$1
Q=$2
p=${P%.*}
q=${Q%.*}

if [ $q -le 0 ]; then
    Q=10
    echo "Q ==" $Q
fi
if [ $p -eq 1 ]; then
    echo  "Компонент A включение рециркуляции"
    halcmd setp gasketing.a.recovery.on True
    halcmd setp gasketing.a.recovery.timer $Q

else
    echo  "Компонент A выключение рециркуляции"
    halcmd setp gasketing.a.recovery.on False
fi

exit 0
