#! /bin/bash
P=$1
Q=$2
p=${P%.*}
if [ $p -eq 1 ]; then
    echo  "Компонент B включение насыщения"
    halcmd setp gasketing.b.saturation.on True
else
    echo  "Компонент B выключение насыщения"
    halcmd setp gasketing.b.saturation.on False
fi

exit 0