#! /bin/bash
P=$1
Q=$2
p=${P%.*}
q=${Q%.*}

if [ $q -le 0 ]; then
    Q=10
    echo "Q ==" $Q
fi
if [ $p -eq 1 ]; then
    echo  "Компонент A включение перемещивания"
    halcmd setp gasketing.a.mixing.on True
    halcmd setp gasketing.a.mixing.timer  $Q

else
    echo  "Компонент A выключение перемещивания"
    halcmd setp gasketing.a.mixing.on False
fi

exit 0
