#! /bin/bash
P=$1
Q=$2
p=${P%.*}
q=${Q%.*}

if [ $q -le 0 ]; then
    Q=10
fi

if [ $p -eq 1 ]; then
    echo  "готовая смесь  подача " $Q 
    halcmd setp gasketing.test.mixture.on True
    halcmd setp gasketing.test.mixture.mass $Q

else
    echo  "готовая смесь завершение подачи  "
    halcmd setp gasketing.test.mixture.on False
fi

exit 0
