#! /bin/bash
P=$1
Q=$2
p=${P%.*}
echo $p
if [ $p -eq 1 ]; then
    halcmd setp gasketing.app.on True
    echo  "Нанесение включение"
else
    halcmd setp gasketing.app.on False
    echo  "Нанесение выключение"
fi

exit 0
