#! /bin/bash
P=$1
Q=$2
p=${P%.*}
q=${Q%.*}
if [ $q -le 0 ]; then
    Q=5000
    echo "Q ==" $Q
fi
if [ $p -eq 1 ]; then
    halcmd setp gasketing.reset-comp.on True
    halcmd setp gasketing.app.feed_nom $Q
    echo  "сброс компонентов включение"
else
    halcmd setp gasketing.reset-comp.on False
    halcmd setp gasketing.app.feed_nom 5000
    echo  "сброс компонентов выключение"
fi

exit 0
