#! /bin/bash
P=$1
Q=$2
p=${P%.*}
if [ $p -eq 1 ]; then
    echo  "Компонент B включение рекуперации"
    halcmd setp gasketing.b.recovery.on True
else
    echo  "Компонент B выключение рекуперации"
    halcmd setp gasketing.b.recovery.on False
fi

exit 0
