#! /bin/bash
P=$1
Q=$2
p=${P%.*}
if [ $p -eq 1 ]; then
    echo  "Компонент B включение перемещивания"
    halcmd setp gasketing.b.mixing.on True
else
    echo  "Компонент B выключение перемещивания"
    halcmd setp gasketing.b.mixing.on False
fi

exit 0