#! /bin/bash
P=$1
Q=$2
p=${P%.*}
q=${Q%.*}

if [ $q -le 0 ]; then
    Q=10
fi
if [ $p -eq 1 ]; then
    echo  "Компонент А подача " $Q 
    halcmd setp gasketing.test.a.on True
    halcmd setp gasketing.test.a.mass $Q

else
    echo  "Компонент А завершение подачи компонета "
    halcmd setp gasketing.test.a.on False
fi

exit 0
